language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  - SECRET_KEY='*E?k<C=E^/$d|Q1XI(7%yU7p)Z*Y9D{x1#sHd(&b:5Tpm^c!6xI?@JT4e]o+sIfQw|r$SGSf0xRdX%`izw}&Duac~5{%5XflYj]!'
script:
  - coverage run --source='naktors,nodes' manage.py test
after_success:
  - coveralls
