# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
