# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_node_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='actor_ref',
            new_name='actor_urn',
        ),
    ]
