# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_auto_20160712_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='actor_urn',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
