# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_auto_20160712_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NodeConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_node', to='nodes.Node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_node', to='nodes.Node')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='node_classes',
            field=models.ManyToManyField(to='nodes.NodeClass'),
        ),
    ]
